BelediyeUlasimProjesi/Controllers/BusController.cs
using BelediyeUlasimProjesi.Data;
using BelediyeUlasimProjesi.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

namespace BelediyeUlasimProjesi.Controllers
{

    public class BusController : Controller
    {
        public readonly BelediyeUlasimProjesiDbContext _context;
        public BusController(BelediyeUlasimProjesiDbContext context)
        {
            _context = context;
        }

        //Otobüsleri Listeleyecek
        public IActionResult List()
        {
            List<Bus> model = _context.Buses.ToList();
            return View(model);
        }
        //Yeni Otobüs Oluşturma Penceresi
        public IActionResult CreateBus()
        {
            ViewBag.TeamDDL = _context.Stations.ToList().Select(u => new SelectListItem
            {
                Selected = false,
                Text = u.StationName,
                Value = u.StationName.ToString()
            }).ToList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateBus(Bus model)
        {
            
            
            if (ModelState.IsValid)
            {
                Station station = _context.Stations.Where(x => x.StationName == model.StationName).First();
                model.StationId = station.Id;
                _context.Buses.Add(model);
                _context.SaveChanges();
                return RedirectToAction("List");
            }

            return View(model);
        }
        //Otobüs Detayları
        public IActionResult Details(int id)
        {
            var model = _context.Buses.Find(id);
            ViewBag.Stops = _context.Stations.ToList().Select(u => new SelectListItem
            {
                Selected = false,
                Text = "Ara Duraklar",
                Value = (u.Durak1, u.Durak2, u.Durak3, u.Durak4, u.Durak5, u.Durak6, u.Durak7, u.Durak8, 
                u.Durak9, u.Durak10, u.Durak11, u.Durak12, u.Durak13, u.Durak14, u.Durak15).ToString()
            });
            return View(model);
        }

        //Otobüs Düzenleme
        public IActionResult Edit(int id)
        {
            Bus model = _context.Buses.Find(id);
            ViewBag.TeamsDDL = _context.Stations.ToList().Select(u => new SelectListItem
            {
                Selected = false,
                Text = u.StationName,
                Value = u.StationName.ToString()
            }).ToList();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Bus model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    Bus willUpdate = _context.Buses.Find(model.Id);
                    willUpdate.BusName = model.BusName;
                    willUpdate.StationName = model.StationName;
                    willUpdate.CreatedDate = DateTime.UtcNow;
                    _context.SaveChanges();
                    return RedirectToAction("List");
                }
                catch (DBConcurrencyException ex)
                {
                    if (_context.Buses.Find(id) == null)
                    {
                        return NotFound();
                    }
                    throw (ex);
                }
            }
            return View();
        }
        //Otobüs Silme İşlemleri
        public IActionResult Delete(int id)
        {
            Bus model = _context.Buses.Find(id);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public IActionResult Delete(int id, Bus model)
        {
            if (_context.Buses.Find(model.Id) == null || id != model.Id)
            {
                return NotFound();
            }
            try
            {
                Bus bus = _context.Buses.Find(id);
                _context.Buses.Remove(bus);
                _context.SaveChanges();
                return RedirectToAction("List");
            }
            catch (DBConcurrencyException ex)
            {
                throw (ex);
            }
        }
    }
}

BelediyeUlasimProjesi/Controllers/StationController.cs
using BelediyeUlasimProjesi.Data;
using BelediyeUlasimProjesi.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace BelediyeUlasimProjesi.Controllers
{
    public class StationController : Controller
    {
        private readonly BelediyeUlasimProjesiDbContext _context;
        public StationController(BelediyeUlasimProjesiDbContext context)
        {
            _context = context;
        }
        public IActionResult List()
        {
            List<Station> list = _context.Stations.ToList();
            return View(list);
        }
        public IActionResult CreateStation()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStation(Station model)
        {
            if (ModelState.IsValid)
            {
                _context.Stations.Add(model);
                _context.SaveChanges();
                return RedirectToAction("List");
            }
            return View(model);
        }
        public IActionResult Details(int id,Station station)
        {
            Station model = _context.Stations.Where(x => x.Id == id).Include(x => x.Buses).FirstOrDefault();
            return View(model);
        }
        public IActionResult Edit(int id)
        {
            Station station = _context.Stations.Find(id);
            ViewBag.TeamDDL = _context.Stations.ToList().Select(u => new SelectListItem
            {
                Selected = false,
                Text = u.StationName,
                Value = u.StationName.ToString()
            });
            return View(station);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Station station)
        {
            if (id != station.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    Station willUpdate = _context.Stations.Find(station.Id);
                    willUpdate.StationName = station.StationName;
                    _context.SaveChanges();
                    return RedirectToAction("List");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (_context.Stations.Find(id) == null)
                    {
                        return NotFound();
                    }
                    throw (ex);
                }
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            Station station = _context.Stations.Find(id);
            return View(station);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id,Station station)
        {
            if (id != station.Id)
            {
                return NotFound();
            }
            try
            {
                if (_context.Buses.Where(x => x.StationName == station.StationName).Any())
                {
                    return NotFound();
                }
                _context.Stations.Remove(station);
                _context.SaveChanges();
                return RedirectToAction("List");
            }
            catch(DbUpdateConcurrencyException ex)
            {
                throw (ex);
            }
        }
        public IActionResult TimeList(int id)
        {
            Station station = _context.Stations.Find(id);
            return View(station);
            
        }
    }
}

BelediyeUlasimProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eskişehir Otobüs Hatları</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <php>
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/StyleSheet.css" />
    </php>
</head>
<body>
    <header >
        <nav style="background-image:url(/images/banner_bg.jpg)" class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container" >
                <button style="background-image:url(/images/logo.png);z-index:1;position:relative; width:334px;height:113px" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></button>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                             <a class="btn btn-light" style="border:2px solid rgb(0, 0, 0)" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-light" style="border:2px solid rgb(0, 0, 0);color:black" asp-area="" asp-controller="Station" asp-action="List">Hatlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-light" style="border:2px solid rgb(0, 0, 0);color:black" asp-area="" asp-controller="Bus" asp-action="List">Otobüsler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-image:url(/images/banner_bg.jpg)" class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Web Master-Egemen Çapacıoğlu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        <div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>